[package]
name = "tessera-backbone"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
tokio = { workspace = true, features = [ "full" ] }
anyhow = { workspace = true }
