edition = "2021"

format_strings = true
max_width = 120
comment_width = 120
reorder_imports = true
use_field_init_shorthand = true
group_imports = "StdExternalCrate"
newline_style = "Unix"
use_small_heuristics = "Max"
