name: Build and push Docker image

on:
  push:
  #   tags:
  #     - "v*"
  # pull_request: # FOR TESTING PURPOSES

jobs:
  ci:
    uses: ./.github/workflows/ci-nebula.yaml

  build:
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      matrix:
        app: [authority, authorization, backbone]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set release version
      #   id: set_version
      #   run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      #   shell: bash

      - name: Set release version
        id: set_version
        run: echo "VERSION=alpha" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./crates/nebula-${{ matrix.app }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cremithq/nebula-${{ matrix.app }}:${{ steps.set_version.outputs.VERSION }}
            ghcr.io/cremithq/nebula-${{ matrix.app }}:latest
