name: CI-nebula

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up toolchain for stable rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install xmlsec1
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install pkg-config libxml2-dev libxmlsec1-dev libxmlsec1-openssl

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: style-check
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -A dead_code

      - name: Run tests
        run: cargo test --all --verbose
